### ISSUE TITLE
build script issue

### ISSUE THREAD

**Issue by joshua1** [hmmhmmhm/svelte-spa-template#1]
Hi @hmmhmmhm  , I tried to run build (npm run build , npm run production-build) in this template and got this error 
```
 /Users/joshuao/Documents/Dev/starters/svelte-spa-template/src/global.css:undefined:undefined: /Users/joshuao/Documents/Dev/starters/svelte-spa-template/node_modules/postcss-reduce-initial contains both .browserslistrc and package.json with browsers
```
on both occasions. running npm run start works ok. can you please have a look?

**Comment by hmmhmmhm** [comment]
Hi! Thank you for the error report! I just checked the errors. I'll fix them in today.

**Comment by hmmhmmhm** [comment]
I fixed this error, there was a problem with the postinstall script.

**Comment by joshua1** [comment]
Thanks @hmmhmmhm it works ok now
