### ISSUE TITLE
image resource usage

### ISSUE THREAD

**Issue by joshua1** [hmmhmmhm/svelte-spa-template#2]
Hi @hmmhmmhm  how is testimage in the resource object supposed to be used (say in an img element) 
```
export const Resources = {
    testImage: require('./images/test-image.png')
}

export default Resources
```

**Comment by hmmhmmhm** [comment]
I am currently developing this template. (Not at the completion stage.) Therefore, there are some unexplained structures, and Resources is a prime example.

You can use Resources as follows. (in svelte-spa-template/src/pages/sample/index.svelte)
```svelte
<script>
    // Component Declaration
    import Page from './index.ts'
    const { Components, Resources, Router, Store } = Page
</script>

<img src={Resources.testImage}/>
```

**Comment by joshua1** [comment]
That was quick. Thanks @hmmhmmhm
